### ISSUE TITLE
Loading error in Godot 4.3 Godot Steam Audio Fork

### ISSUE THREAD

**Issue by ismailivanov** [JekSun97/gdTree3D#12]
![resim](https://github.com/user-attachments/assets/cd85cdac-0b92-4378-93bf-ad215d1a5b3d)

https://github.com/stechyo/godot/releases/tag/4.3-steam-audio

**Comment by ismailivanov** [comment]
![resim](https://github.com/user-attachments/assets/94acfd28-1f60-45fa-ae58-4d9facff895c)
![resim](https://github.com/user-attachments/assets/74adc384-4edc-450a-8e36-cb02676bb3fe)

**Comment by FibreFoX** [comment]
@ismailgamedev Please rename the SO files to match the filename in your error message. The last release contains some mistakes, will probably be fixed with the next GitHub release.

**Comment by FibreFoX** [comment]
Should be `libTree3D.linux.template_*.x86_64.so` instead of `libtree3d.linux.template_*.x86_64.so` (with capital T and capital D)

**Comment by ismailivanov** [comment]
Thanks
