### ISSUE TITLE
Godot 4.3 crashes when I switch between scene in the editor.

### ISSUE THREAD

**Issue by ismailivanov** [JekSun97/gdTree3D#14]
![image](https://github.com/user-attachments/assets/021e1a21-8d57-4834-8ab9-c81116ed4917)
It just crashes when the Tree3D plugin is in my scene. It works in the game but crashes when I switch between scenes in the editor. And it doesn't crash when I switch to the other scene, it crashes when I switch to the other scene and come back to the scene with the Tree3D plugin.

**Comment by FibreFoX** [comment]
Maybe the same as #13 ?
