### ISSUE TITLE
other operating systems

### ISSUE THREAD

**Issue by MachinistJohn** [JekSun97/gdTree3D#3]
Not everyone uses windows, how about for linux and mac as well?

**Comment by JekSun97** [comment]
@MachinistJohn  I'm sorry, but I don't have these operating systems available to post ready-made assemblies for them, but the plugin supports them, you can build them yourself using SCons and send them to me, I'll be happy to add them to the release version

**Comment by Smorty10** [comment]
I've just built the plugin just now for GNU/Linux for debug and release.
[libtree3d.linux.template_.zip](https://github.com/user-attachments/files/16221508/libtree3d.linux.template_.zip)


BUT! I personally don't use windows, but I would strongly urge @JekSun97 to try to build it on their own machine. Please Try `scons platform=linux` on your machine! I have had difficulties compiling windows and mac binaries on GNU/Linux, but maybe the compotebility is better from windows to GNU since GNU is FOSS and stuff...

**Comment by FibreFoX** [comment]
@JekSun97 you could try to use the Github runners to build these files, makes it more reproducable AND available for all operating systems

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

**Comment by JekSun97** [comment]
> I've just built the plugin just now for GNU/Linux for debug and release.
> [libtree3d.linux.template_.zip](https://github.com/user-attachments/files/16221508/libtree3d.linux.template_.zip)

@Smorty10  Thank you! While I'm about to release the new version, could you please compile "Master" with the new changes so I can release it.

**Comment by JekSun97** [comment]
> @JekSun97 you could try to use the Github runners to build these files, makes it more reproducable AND available for all operating systems
> 
> https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

To be honest, this is the first time I've heard about this :)
I'll figure this out in a few days and try to put something together, thanks

**Comment by FibreFoX** [comment]
@JekSun97 They are just some YAML files, where you configure "reproducable steps" for the github provided build servers. By using some "magic", you even can create releases. But it removes the need for your device having installed all the needed stuff (or even having to have the other OS installed).

I might look into helping with this, if needed 😸

**Comment by Malidos** [comment]
Here are both up to date build templates for macOS (Apple Silicone and Intel architecture). They are unsigned so you need to bypass Apples security hoops.
[libtree3d.macos.template_.framework.zip](https://github.com/user-attachments/files/16732373/libtree3d.macos.template_.framework.zip)

Sadly, the Linux builds kept failing, otherwise I would have uploaded them as well.

**Comment by FibreFoX** [comment]
@Malidos What is the command you've used to create the binaries for supporting Apple Silicon & Intel?

**Comment by Malidos** [comment]
> @Malidos What is the command you've used to create the binaries for supporting Apple Silicon & Intel?

You build separately for arm64 and x86_64 architecture and then combine both libraries using the lipo command on macOS. It's also described in the official build instructions [Compiling for macOS](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_macos.html).

**Comment by FibreFoX** [comment]
@Malidos Thanks a lot, I will try to incorporate these steps in my Github Actions pipeline. Never done that before, so its a new topic for me.

**Comment by FibreFoX** [comment]
This was closed "by accident" while merging #5 too early. @JekSun97 can you re-open until my Github Actions stuff is finished?

**Comment by FibreFoX** [comment]
@Malidos @Smorty10 @JekSun97 Hi, can you check on your end, that these compiled binaries do work for you? These were created by my Github Actions workflow: https://github.com/FibreFoX/gdTree3D/actions/runs/10566459287

Just scroll down and find the binaries that are fitting for your needs. Would help me a lot to verify that I am on the right way.

In case you have no access (not THAT familiar with GH Actions yet), I've added them here too:
[binaries-linux-godot4.1-x86_32.zip](https://github.com/user-attachments/files/16753445/binaries-linux-godot4.1-x86_32.zip)
[binaries-linux-godot4.1-x86_64.zip](https://github.com/user-attachments/files/16753446/binaries-linux-godot4.1-x86_64.zip)
[binaries-linux-godot4.2-x86_32.zip](https://github.com/user-attachments/files/16753447/binaries-linux-godot4.2-x86_32.zip)
[binaries-linux-godot4.2-x86_64.zip](https://github.com/user-attachments/files/16753448/binaries-linux-godot4.2-x86_64.zip)
[binaries-linux-godot4.3-x86_32.zip](https://github.com/user-attachments/files/16753449/binaries-linux-godot4.3-x86_32.zip)
[binaries-linux-godot4.3-x86_64.zip](https://github.com/user-attachments/files/16753450/binaries-linux-godot4.3-x86_64.zip)
[binaries-macos-godot4.1.zip](https://github.com/user-attachments/files/16753451/binaries-macos-godot4.1.zip)
[binaries-macos-godot4.2.zip](https://github.com/user-attachments/files/16753452/binaries-macos-godot4.2.zip)
[binaries-macos-godot4.3.zip](https://github.com/user-attachments/files/16753453/binaries-macos-godot4.3.zip)
[binaries-windows-godot4.1-x86_32.zip](https://github.com/user-attachments/files/16753454/binaries-windows-godot4.1-x86_32.zip)
[binaries-windows-godot4.1-x86_64.zip](https://github.com/user-attachments/files/16753455/binaries-windows-godot4.1-x86_64.zip)
[binaries-windows-godot4.2-x86_32.zip](https://github.com/user-attachments/files/16753456/binaries-windows-godot4.2-x86_32.zip)
[binaries-windows-godot4.2-x86_64.zip](https://github.com/user-attachments/files/16753457/binaries-windows-godot4.2-x86_64.zip)
[binaries-windows-godot4.3-x86_32.zip](https://github.com/user-attachments/files/16753458/binaries-windows-godot4.3-x86_32.zip)
[binaries-windows-godot4.3-x86_64.zip](https://github.com/user-attachments/files/16753459/binaries-windows-godot4.3-x86_64.zip)

**Comment by Malidos** [comment]
My macOS system could read all binaries successfully. I don't think they were any compile issues.

**Comment by FibreFoX** [comment]
@Malidos Do you mean "using the binaries that were provided" worked? I don't have access to a MacOS system with Apple Silicon, so I assumed maybe you have (because you provided files before).

EDIT: changed my answer ;) did not read properly at first

**Comment by Malidos** [comment]
> @Malidos Do you mean "using the binaries that were provided" worked? I don't have access to a MacOS system with Apple Silicon, so I assumed maybe you have (because you provided files before).

The provided binaries macOS worked, at least those for x86_64. I can't test for Apple Silicone either.
With simple build commands there isn't much that can go wrong with Scons on an macOS emulator.

**Comment by FibreFoX** [comment]
This time this issue should be solved ;)
